### ISSUE TITLE
[BUG] - newlines binnen <a> tag worden meegenomen in de hyperlink 

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-link-list#100]
**Omschrijf het probleem**
Wanneer er in de code newlines gezet worden binnen de <a> tag, voor leesbaarheid, worden deze meegenomen in de hyperlink en lijkt het alsof er een spatie zit in de tekst van de link.

**Hoe te reproduceren**
```
<ul is="vl-link-list" id="link-list">
          <li is="vl-link-list-item">
            <a is="vl-link" href="/grup-procedure">
              Wat is een Gewestelijk Ruimtelijk Uitvoeringsplan
            </a>
          </li>
          <li is="vl-link-list-item">
            <a is="vl-link" href="/hoe-inspreken">
              Hoe kan ik een inspraakreactie indienen
            </a>
          </li>          
          <li is="vl-link-list-item">
            <a is="vl-link" href="/inspraak-verwerking">
              Wat gebeurt er met mijn inspraakreactie
            </a>
          </li>
          <li is="vl-link-list-item">
            <a is="vl-link" href="/bezwaar-verwerking">
              Wat gebeurt er met mijn bezwaar
            </a>
          </li>
        </ul>
```
Wanneer de newlines weggedaan worden, is het in orde. 

**Gewenst gedrag**
Dat de newlines kunnen blijven zonder dat deze meegenomen worden in de hyperlink. 

**Screenshots**
Met newlines:
<img width="1272" alt="Screenshot 2021-01-15 at 12 43 17" src="https://user-images.githubusercontent.com/8820456/104723659-e448fc80-572f-11eb-9d37-6b732f0ecf3d.png">

Zonder newlines:
<img width="1242" alt="Screenshot 2021-01-15 at 12 48 44" src="https://user-images.githubusercontent.com/8820456/104723801-135f6e00-5730-11eb-96e5-67befaafb6f7.png">

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome en safari

**Comment by coemans** [comment]
Probleem is niet meer reproduceerbaar in de laatste versie, werd bijgevolg opgelost door een upgrade.
