### ISSUE TITLE
[TASK] - De vl-link-list component wordt anders opgebouwd dan bij webuniversum

### ISSUE THREAD

**Issue by wautergu** [milieuinfo/webcomponent-vl-ui-link-list#60]
**Beschrijving**
De componenten van webuniversum worden anders opgebouwd dan de onze. Nakijken waarom en ev. aanpassen.

**Comment by kevcraey** [comment]
kan je dat wat verduidelijken aub @wautergu? Wat is er anders en wat zijn de gevolgen (nadelen) ervan?

**Comment by wautergu** [comment]
Ik weet niet goed meer wat ik bedoelde. Maar als ik het nu zo bekijk, zie ik niet zo'n noemenswaardige verschillen. Behalve dat wij als icon-element een 'span' (die een icon is) gebruiken en webuniversion een 'i'.

Wellicht kan dat geen kwaad.
